import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import prettier from 'eslint-config-prettier/flat'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // shadcn-generated primitives in `components/ui/**` follow upstream React patterns
  // and are regenerated by the shadcn CLI (not hand-authored), so we relax the React 19
  // `set-state-in-effect` rule there only — our own code still enforces it.
  {
    files: ['components/ui/**'],
    rules: { 'react-hooks/set-state-in-effect': 'off' },
  },
  // Turn OFF any ESLint rules that conflict with Prettier. MUST stay last so its
  // disables win over rules enabled above. Prettier owns formatting; ESLint owns code quality.
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
  ]),
])

export default eslintConfig
