export { AdSlot } from './components/ad-slot'
export { AdvertisingProvider } from './contexts/advertising-provider'
export { useAdvertising } from './hooks/use-advertising'
export { useCardAdViewport } from './hooks/use-card-ad-viewport'
export { adPlacement, FEED_GAMES_PER_AD, MAX_FEED_ADS, type AdPlacement } from './config/placements'
