import {
  AxeIcon,
  BackpackIcon,
  BellIcon,
  BookOpenIcon,
  BotIcon,
  BowArrowIcon,
  CalendarDaysIcon,
  CameraIcon,
  CarIcon,
  ClockIcon,
  CloudIcon,
  CompassIcon,
  CrownIcon,
  EyeIcon,
  FilmIcon,
  FlameIcon,
  FlagIcon,
  Gamepad2Icon,
  GemIcon,
  GhostIcon,
  GiftIcon,
  Globe2Icon,
  HammerIcon,
  HeartIcon,
  HourglassIcon,
  HouseIcon,
  JoystickIcon,
  KeyRoundIcon,
  LightbulbIcon,
  LockIcon,
  MapIcon,
  MedalIcon,
  MegaphoneIcon,
  MountainIcon,
  MusicIcon,
  OrbitIcon,
  OrigamiIcon,
  PaletteIcon,
  PencilIcon,
  PlaneIcon,
  RocketIcon,
  ScissorsIcon,
  SettingsIcon,
  ShieldIcon,
  ShipIcon,
  SkullIcon,
  SnowflakeIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  SwordIcon,
  TargetIcon,
  ThumbsUpIcon,
  TrophyIcon,
  WrenchIcon,
  ZapIcon,
  type LucideIcon,
} from 'lucide-react'
import { z } from 'zod'

export const libraryListIconSchema = z.enum([
  'GAMEPAD',
  'CONTROLLER',
  'ARCADE',
  'SWORD',
  'SHIELD',
  'BOW',
  'AXE',
  'DAGGER',
  'ALIEN',
  'ROBOT',
  'GHOST',
  'SKULL',
  'DRAGON',
  'STAR',
  'FIRE',
  'HEART',
  'DIAMOND',
  'CROWN',
  'CAR',
  'ROCKET',
  'AIRPLANE',
  'SHIP',
  'MUSIC',
  'PALETTE',
  'CAMERA',
  'BOOK',
  'FILM',
  'TOOL',
  'GEAR',
  'WRENCH',
  'KEY',
  'LOCK',
  'TARGET',
  'TROPHY',
  'MEDAL',
  'FLAG',
  'BELL',
  'CLOUD',
  'SUN',
  'MOON',
  'LIGHTNING',
  'SNOWFLAKE',
  'HOME',
  'MAP',
  'COMPASS',
  'GLOBE',
  'MOUNTAIN',
  'SPARKLES',
  'ZAP',
  'HOURGLASS',
  'CLOCK',
  'CALENDAR',
  'BACKPACK',
  'EYE',
  'THUMBS_UP',
  'MEGAPHONE',
  'LIGHTBULB',
  'PENCIL',
  'SCISSORS',
  'GIFT',
])

export type LibraryListIcon = z.infer<typeof libraryListIconSchema>

export const DEFAULT_LIBRARY_LIST_ICON: LibraryListIcon = 'GAMEPAD'

export const LIBRARY_LIST_ICONS: Record<LibraryListIcon, LucideIcon> = {
  GAMEPAD: Gamepad2Icon,
  CONTROLLER: Gamepad2Icon,
  ARCADE: JoystickIcon,
  SWORD: SwordIcon,
  SHIELD: ShieldIcon,
  BOW: BowArrowIcon,
  AXE: AxeIcon,
  DAGGER: SwordIcon,
  ALIEN: OrbitIcon,
  ROBOT: BotIcon,
  GHOST: GhostIcon,
  SKULL: SkullIcon,
  DRAGON: OrigamiIcon,
  STAR: StarIcon,
  FIRE: FlameIcon,
  HEART: HeartIcon,
  DIAMOND: GemIcon,
  CROWN: CrownIcon,
  CAR: CarIcon,
  ROCKET: RocketIcon,
  AIRPLANE: PlaneIcon,
  SHIP: ShipIcon,
  MUSIC: MusicIcon,
  PALETTE: PaletteIcon,
  CAMERA: CameraIcon,
  BOOK: BookOpenIcon,
  FILM: FilmIcon,
  TOOL: HammerIcon,
  GEAR: SettingsIcon,
  WRENCH: WrenchIcon,
  KEY: KeyRoundIcon,
  LOCK: LockIcon,
  TARGET: TargetIcon,
  TROPHY: TrophyIcon,
  MEDAL: MedalIcon,
  FLAG: FlagIcon,
  BELL: BellIcon,
  CLOUD: CloudIcon,
  SUN: SunIcon,
  MOON: OrbitIcon,
  LIGHTNING: ZapIcon,
  SNOWFLAKE: SnowflakeIcon,
  HOME: HouseIcon,
  MAP: MapIcon,
  COMPASS: CompassIcon,
  GLOBE: Globe2Icon,
  MOUNTAIN: MountainIcon,
  SPARKLES: SparklesIcon,
  ZAP: ZapIcon,
  HOURGLASS: HourglassIcon,
  CLOCK: ClockIcon,
  CALENDAR: CalendarDaysIcon,
  BACKPACK: BackpackIcon,
  EYE: EyeIcon,
  THUMBS_UP: ThumbsUpIcon,
  MEGAPHONE: MegaphoneIcon,
  LIGHTBULB: LightbulbIcon,
  PENCIL: PencilIcon,
  SCISSORS: ScissorsIcon,
  GIFT: GiftIcon,
}

export function getLibraryListIcon(icon: string): LucideIcon | undefined {
  const parsed = libraryListIconSchema.safeParse(icon)
  return parsed.success ? LIBRARY_LIST_ICONS[parsed.data] : undefined
}
